/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * Sample API
 * Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
 * OpenAPI spec version: 0.1.9
 */

