/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * Sample API
 * Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
 * OpenAPI spec version: 0.1.9
 */
import axios from 'axios'
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios'




  /**
 * Optional extended description in CommonMark or HTML.
 * @summary Returns a list of users.
 */
export const getContactsPhp = <TData = AxiosResponse<string[]>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/contacts.php`,options
    );
  }
