openapi: 3.0.0
info:
  title: Sample API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9
servers:
  - url: https://test.k6.io/
    description: Optional server description, e.g. Main (production) server
paths:
  /contacts.php:
    get:
      summary: Returns a list of users.
      description: Optional extended description in CommonMark or HTML.
      responses:
        "200": # status code
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
